# Generated by Django 6.0.1 on 2026-01-28 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=70)),
                ('country', models.CharField(help_text='Three letter country code, eg. POL, GER, ENG', max_length=3)),
                ('founding_year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(help_text='Three letter country code, eg. POL, GER, ENG', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=70)),
                ('foundation_year', models.PositiveIntegerField()),
                ('stadium', models.CharField(max_length=70)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_tracker.league')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='football_tracker.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(help_text='Three letter country code, eg. POL, GER, ENG', max_length=3)),
                ('preffered_foot', models.CharField(choices=[('R', 'Right'), ('L', 'Left')], max_length=1)),
                ('height', models.PositiveIntegerField(help_text='Player height (in cm)')),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward')], default='GK', max_length=2)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='football_tracker.club')),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='top_scorer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='football_tracker.player'),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('winner_score', models.PositiveIntegerField()),
                ('second_place_score', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=70)),
                ('venue', models.CharField(max_length=70)),
                ('final_second_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_second_place', to='football_tracker.club')),
                ('final_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_winner', to='football_tracker.club')),
                ('man_of_the_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='football_tracker.player')),
            ],
        ),
    ]
