# Generated by Django 6.0.1 on 2026-01-28 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_tracker', '0002_alter_club_league'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['last_name']},
        ),
    ]
