# Generated by Django 6.0.1 on 2026-01-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_tracker', '0003_alter_player_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='second_place_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='winner_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
